# Generated by Django 5.1.2 on 2024-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_sign_up_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
