# Generated by Django 5.1.2 on 2024-11-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_last_name_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sign_up_method',
            field=models.CharField(default='google', max_length=10),
        ),
    ]
