# Generated by Django 5.1.2 on 2024-10-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road_quality', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoadImages',
            new_name='RoadImage',
        ),
    ]
