# Generated by Django 5.1.2 on 2024-11-06 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_quality', '0002_rename_roadimages_roadimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roadimage',
            name='device_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadimage',
            name='location_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
