# Generated by Django 5.1.2 on 2024-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_quality', '0003_roadimage_device_info_roadimage_location_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadimage',
            old_name='road_image',
            new_name='road_image_filename',
        ),
        migrations.AddField(
            model_name='roadimage',
            name='road_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
